esphome:
  name: esp-wifi-sensing-disabled
  friendly_name: ESP WiFi Sensing Disabled

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:

wifi:
  ssid: "wifi-sensing-test"
  password: "wifi-sensing-test"
  ap:
    ssid: "WiFi Sensing Disabled Fallback"
    password: "wifi-sensing-test"

external_components:
  - source:
      type: local
      path: ..

esp_wifi_sensing:
  id: wifi_sensing
  gain_compensation: false
  threshold: 6000
  debounce: 2
  adaptive_threshold: true
  sigma_multiplier: 4.0
  baseline_rise_time: 30min
  baseline_fall_time: 30min
  learning_delay: 60s

sensor:
  - platform: esp_wifi_sensing
    esp_wifi_sensing_id: wifi_sensing
    metric:
      name: "CSI Metric"
    variation_avg:
      name: "CSI Variation Avg"
    baseline_mean:
      name: "Baseline Mean"
    baseline_stddev:
      name: "Baseline StdDev"
    adaptive_threshold:
      name: "Adaptive Threshold"


binary_sensor:
  - platform: esp_wifi_sensing
    esp_wifi_sensing_id: wifi_sensing
    motion:
      name: "CSI Motion"
